# Generated by Django 4.1 on 2022-08-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espdata',
            name='value',
        ),
    ]
